### ISSUE TITLE
About implementation detail

### ISSUE THREAD

**Issue by ngoductuanlhp** [KAIST-VICLab/cloud_nerf#5]
Hi @quan5609, thank you for your great repo. I would like to ask several questions about the technical details:

1. How long does it takes to train a single scene of the LLFF dataset?
2. How to obtain the camera poses of the LLFF dataset? Take from the dataset itself or use COLMAP?

Looking forward to your reply. Thanks!

**Comment by quan5609** [comment]
Hi @ngoductuanlhp,

1. The training time depends on the number of training frames of each specific scene. It took us about 7 hours to train 17 frames of Fern scene on TitanXP.
2. We use the same COLMAP preprocess pipeline from the original LLFF repo https://github.com/Fyusion/LLFF to obtain the camera poses from sparse images.
