### ISSUE TITLE
[Question] Results on other datasets

### ISSUE THREAD

**Issue by wonozlo** [KAIST-VICLab/cloud_nerf#6]
Hi, thanks for your great work!
I think your point cloud based NerF should make training much faster than other 3D volume rendering methods.
I have one question about your work.
Is there any results on other datasets rather than LLFF dataset?

Best regrads.

**Comment by quan5609** [comment]
Hello @wonozlo,
Currently, we only conduct experiments on the LLFF dataset. We'll provide the results on DTU and ScanNet in future updates.
