### ISSUE TITLE
Question about inference time

### ISSUE THREAD

**Issue by ChaeyeonSon** [KAIST-VICLab/cloud_nerf#7]
Thanks for your good code implementation! 

It looks easy to understand and utilize.

However, I wonder if the inference time of this implementation is faster than the previous NeRF.

Thanks.

**Comment by quan5609** [comment]
Our method only shows better training convergence than NeRF. For inference, there is no significant difference. In future updates, we will provide the Cuda implementation for neural points query to optimize the inference time.
