### ISSUE TITLE
[Question] Capacity of the point cloud

### ISSUE THREAD

**Issue by dayna-k** [KAIST-VICLab/cloud_nerf#9]
Hi! 
Thanks for sharing your cloud nerf code which is neatly arranged.
I have started working with your wonderful code and want to put my own input files to see how they work using your cloud approach.
There are two questions before that.

1) How much capacity of the point cloud in your method?
2) I think that the larger the scene, the larger the capacity of the point cloud would be needed, how can you handle the burden?

**Comment by quan5609** [comment]
1. The number of points cloud is fixed at 8192 for the entire dataset.
2.  It's true that different scenes require different optimal numbers of points. In this work, we employ the furthest points sampling algorithm to best represent the scene with a fixed number of points
